// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserStore is an autogenerated mock type for the UserStore type
type UserStore struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, u
func (_m *UserStore) Create(ctx context.Context, u interface{}) (string, error) {
	ret := _m.Called(ctx, u)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) string); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *UserStore) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id, u
func (_m *UserStore) Get(ctx context.Context, id string, u interface{}) error {
	ret := _m.Called(ctx, id, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, id, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByTelegramID provides a mock function with given fields: ctx, telegramID, u
func (_m *UserStore) GetByTelegramID(ctx context.Context, telegramID int, u interface{}) (string, error) {
	ret := _m.Called(ctx, telegramID, u)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, int, interface{}) string); ok {
		r0 = rf(ctx, telegramID, u)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, interface{}) error); ok {
		r1 = rf(ctx, telegramID, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
